--Who is the manager of Neena

select EMPLOYEE_ID,FIRST_NAME,LAST_NAME,MANAGER_ID
from EMPLOYEES;

select w.EMPLOYEE_ID,w.FIRST_NAME,w.LAST_NAME,w.MANAGER_ID,m.EMPLOYEE_ID, m.FIRST_NAME,m.LAST_NAME
from EMPLOYEES W join EMPLOYEES M
on w.MANAGER_ID = m.EMPLOYEE_ID;
